# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Spine_Broken.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(588, 497)
        MainWindow.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.header_frame = QtWidgets.QFrame(self.central_widget)
        self.header_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.header_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_frame.setObjectName("header_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.header_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.header_left_frame = QtWidgets.QFrame(self.header_frame)
        self.header_left_frame.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.header_left_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.header_left_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.header_left_frame.setObjectName("header_left_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header_left_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.header = QtWidgets.QLabel(self.header_left_frame)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.header.setFont(font)
        self.header.setStyleSheet("color: #fff;")
        self.header.setObjectName("header")
        self.horizontalLayout_4.addWidget(self.header)
        self.horizontalLayout_3.addWidget(self.header_left_frame)
        self.top_right_btns = QtWidgets.QFrame(self.header_frame)
        self.top_right_btns.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton{\n"
"    border-radius: 5px;\n"
"    background-color: #76a5af;\n"
"}\n"
"\n"
"QFrame{\n"
"    background-color: #76a5af;\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_button = QtWidgets.QPushButton(self.top_right_btns)
        self.minimize_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_button.setIcon(icon)
        self.minimize_button.setIconSize(QtCore.QSize(24, 24))
        self.minimize_button.setObjectName("minimize_button")
        self.horizontalLayout_2.addWidget(self.minimize_button)
        self.restore_button = QtWidgets.QPushButton(self.top_right_btns)
        self.restore_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/cil-window-restore.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restore_button.setIcon(icon1)
        self.restore_button.setIconSize(QtCore.QSize(24, 24))
        self.restore_button.setObjectName("restore_button")
        self.horizontalLayout_2.addWidget(self.restore_button)
        self.close_button = QtWidgets.QPushButton(self.top_right_btns)
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setIconSize(QtCore.QSize(24, 24))
        self.close_button.setObjectName("close_button")
        self.horizontalLayout_2.addWidget(self.close_button)
        self.horizontalLayout_3.addWidget(self.top_right_btns)
        self.verticalLayout_2.addWidget(self.header_frame)
        self.frame_mian_body = QtWidgets.QFrame(self.central_widget)
        self.frame_mian_body.setStyleSheet("QFrame{\n"
"    background-color: #4F4F4F\n"
"}")
        self.frame_mian_body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_mian_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_mian_body.setObjectName("frame_mian_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_mian_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_mian_body)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.frame_left_menu.setFont(font)
        self.frame_left_menu.setStyleSheet("QFrame{\n"
"    font: 9pt \"Verdana\";\n"
"    background-color: rgb(102, 102, 102);\n"
"}\n"
"QPushButton{\n"
"    padding: 5px 10px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color: rgb(102, 102, 102);\n"
"    color: #fff;\n"
"    padding-left: 30px;\n"
"}\n"
"QLabel{\n"
"    color: #fff;\n"
"}")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(12, -1, -1, -1)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.menu_toggle = QtWidgets.QPushButton(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menu_toggle.sizePolicy().hasHeightForWidth())
        self.menu_toggle.setSizePolicy(sizePolicy)
        self.menu_toggle.setMinimumSize(QtCore.QSize(150, 0))
        self.menu_toggle.setMaximumSize(QtCore.QSize(16777177, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.menu_toggle.setFont(font)
        self.menu_toggle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.menu_toggle.setStyleSheet("background-image:url(:/icons/icons/cil-menu.png);\n"
"background-repeat: none;\n"
"padding-left: 30px;\n"
"background-position: center left")
        self.menu_toggle.setIconSize(QtCore.QSize(48, 48))
        self.menu_toggle.setFlat(True)
        self.menu_toggle.setObjectName("menu_toggle")
        self.verticalLayout_3.addWidget(self.menu_toggle, 0, QtCore.Qt.AlignLeft)
        self.add_patient = QtWidgets.QPushButton(self.frame_left_menu)
        self.add_patient.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.add_patient.setFont(font)
        self.add_patient.setStyleSheet("background-image: url(:/icons/icons/cil-user-follow.png);\n"
"background-repeat: none;\n"
"background-position: center left;\n"
"padding-left:50px;")
        self.add_patient.setIconSize(QtCore.QSize(24, 24))
        self.add_patient.setFlat(True)
        self.add_patient.setObjectName("add_patient")
        self.verticalLayout_3.addWidget(self.add_patient, 0, QtCore.Qt.AlignLeft)
        self.line_1 = QtWidgets.QFrame(self.frame_left_menu)
        self.line_1.setMaximumSize(QtCore.QSize(16777174, 16777215))
        self.line_1.setStyleSheet("color: #fff;")
        self.line_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_1.setLineWidth(1)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setObjectName("line_1")
        self.verticalLayout_3.addWidget(self.line_1)
        self.search = QtWidgets.QPushButton(self.frame_left_menu)
        self.search.setEnabled(True)
        self.search.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.search.setFont(font)
        self.search.setStyleSheet("background-image: url(:/icons/icons/icons8-search-32.png);\n"
"background-repeat: none;\n"
"background-position: center left;")
        self.search.setIconSize(QtCore.QSize(24, 24))
        self.search.setFlat(True)
        self.search.setObjectName("search")
        self.verticalLayout_3.addWidget(self.search, 0, QtCore.Qt.AlignLeft)
        self.line_2 = QtWidgets.QFrame(self.frame_left_menu)
        self.line_2.setStyleSheet("color: #fff;")
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_3.addWidget(self.line_2)
        self.patients = QtWidgets.QPushButton(self.frame_left_menu)
        self.patients.setEnabled(False)
        self.patients.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.patients.setFont(font)
        self.patients.setStyleSheet("background-image: url(:/icons/icons/cil-people.png);\n"
"background-repeat: none;\n"
"background-position: center left;")
        self.patients.setIconSize(QtCore.QSize(24, 24))
        self.patients.setFlat(True)
        self.patients.setObjectName("patients")
        self.verticalLayout_3.addWidget(self.patients, 0, QtCore.Qt.AlignLeft)
        self.line_3 = QtWidgets.QFrame(self.frame_left_menu)
        self.line_3.setStyleSheet("color: #fff;")
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_3.addWidget(self.line_3)
        self.patient_list = QtWidgets.QListWidget(self.frame_left_menu)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.patient_list.setFont(font)
        self.patient_list.setStyleSheet("color : #fff;")
        self.patient_list.setObjectName("patient_list")
        item = QtWidgets.QListWidgetItem()
        self.patient_list.addItem(item)
        self.verticalLayout_3.addWidget(self.patient_list)
        self.horizontalLayout.addWidget(self.frame_left_menu, 0, QtCore.Qt.AlignLeft)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_mian_body)
        self.stackedWidget.setStyleSheet("background-color: #4F4F4F;")
        self.stackedWidget.setLineWidth(0)
        self.stackedWidget.setObjectName("stackedWidget")
        self.recently_viewed_page = QtWidgets.QWidget()
        self.recently_viewed_page.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.recently_viewed_page.setObjectName("recently_viewed_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.recently_viewed_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.recently_viewed = QtWidgets.QLabel(self.recently_viewed_page)
        self.recently_viewed.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(36)
        self.recently_viewed.setFont(font)
        self.recently_viewed.setObjectName("recently_viewed")
        self.verticalLayout.addWidget(self.recently_viewed, 0, QtCore.Qt.AlignHCenter)
        self.recently_list = QtWidgets.QListWidget(self.recently_viewed_page)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.recently_list.setFont(font)
        self.recently_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.recently_list.setObjectName("recently_list")
        self.verticalLayout.addWidget(self.recently_list)
        self.tool_box_empty = QtWidgets.QFrame(self.recently_viewed_page)
        self.tool_box_empty.setMinimumSize(QtCore.QSize(0, 70))
        self.tool_box_empty.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tool_box_empty.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(118, 165, 175);\n"
"}\n"
"")
        self.tool_box_empty.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tool_box_empty.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tool_box_empty.setObjectName("tool_box_empty")
        self.verticalLayout.addWidget(self.tool_box_empty)
        self.stackedWidget.addWidget(self.recently_viewed_page)
        self.search_page = QtWidgets.QWidget()
        self.search_page.setStyleSheet("QLabel{\n"
"    color: #fff;\n"
"}")
        self.search_page.setObjectName("search_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.search_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.patients_label = QtWidgets.QLabel(self.search_page)
        self.patients_label.setMinimumSize(QtCore.QSize(0, 60))
        self.patients_label.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(36)
        self.patients_label.setFont(font)
        self.patients_label.setAlignment(QtCore.Qt.AlignCenter)
        self.patients_label.setObjectName("patients_label")
        self.verticalLayout_4.addWidget(self.patients_label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.search_no_label = QtWidgets.QLabel(self.search_page)
        self.search_no_label.setMinimumSize(QtCore.QSize(100, 40))
        self.search_no_label.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.search_no_label.setFont(font)
        self.search_no_label.setAlignment(QtCore.Qt.AlignCenter)
        self.search_no_label.setObjectName("search_no_label")
        self.horizontalLayout_5.addWidget(self.search_no_label)
        self.input_no = QtWidgets.QLineEdit(self.search_page)
        self.input_no.setMinimumSize(QtCore.QSize(100, 40))
        self.input_no.setMaximumSize(QtCore.QSize(100, 40))
        self.input_no.setStyleSheet("color: #fff;")
        self.input_no.setClearButtonEnabled(True)
        self.input_no.setObjectName("input_no")
        self.horizontalLayout_5.addWidget(self.input_no)
        self.search_no_button = QtWidgets.QPushButton(self.search_page)
        self.search_no_button.setMinimumSize(QtCore.QSize(40, 40))
        self.search_no_button.setMaximumSize(QtCore.QSize(40, 40))
        self.search_no_button.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.search_no_button.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/icons8-search-32.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_no_button.setIcon(icon3)
        self.search_no_button.setIconSize(QtCore.QSize(24, 24))
        self.search_no_button.setFlat(True)
        self.search_no_button.setObjectName("search_no_button")
        self.horizontalLayout_5.addWidget(self.search_no_button)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.no_list = QtWidgets.QListWidget(self.search_page)
        self.no_list.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.no_list.setFont(font)
        self.no_list.setStyleSheet("color: #fff;\n"
"padding-left: 50px;\n"
"margin:50px;")
        self.no_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.no_list.setObjectName("no_list")
        self.verticalLayout_4.addWidget(self.no_list)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.tool_box_empty_2 = QtWidgets.QFrame(self.search_page)
        self.tool_box_empty_2.setMinimumSize(QtCore.QSize(0, 70))
        self.tool_box_empty_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tool_box_empty_2.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(118, 165, 175);\n"
"}\n"
"")
        self.tool_box_empty_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tool_box_empty_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tool_box_empty_2.setObjectName("tool_box_empty_2")
        self.verticalLayout_5.addWidget(self.tool_box_empty_2)
        self.stackedWidget.addWidget(self.search_page)
        self.thumbnail_page = QtWidgets.QWidget()
        self.thumbnail_page.setObjectName("thumbnail_page")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.thumbnail_page)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.thumbnail_page)
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setMinimumSize(QtCore.QSize(150, 0))
        self.frame.setMaximumSize(QtCore.QSize(100, 16777215))
        self.frame.setStyleSheet("background-color: rgb(153, 153, 153);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.thumbnail_list = QtWidgets.QListWidget(self.frame)
        self.thumbnail_list.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.thumbnail_list.setObjectName("thumbnail_list")
        self.verticalLayout_8.addWidget(self.thumbnail_list)
        self.horizontalLayout_6.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.page)
        self.frame_2.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.photo = QtWidgets.QLabel(self.frame_2)
        self.photo.setObjectName("photo")
        self.gridLayout.addWidget(self.photo, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_2)
        self.stackedWidget_2.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget_2.addWidget(self.page_2)
        self.verticalLayout_7.addWidget(self.stackedWidget_2)
        self.tool_box_2 = QtWidgets.QFrame(self.thumbnail_page)
        self.tool_box_2.setMinimumSize(QtCore.QSize(70, 70))
        self.tool_box_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.tool_box_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(118, 165, 175);\n"
"}\n"
"QPushButton{\n"
"    background-color: rgb(118, 165, 175);\n"
"}\n"
"")
        self.tool_box_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tool_box_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tool_box_2.setObjectName("tool_box_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.tool_box_2)
        self.horizontalLayout_7.setContentsMargins(12, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (13).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon4)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setFlat(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_7.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_2.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (9).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon5)
        self.pushButton_2.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_7.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_3.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon6)
        self.pushButton_3.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_7.addWidget(self.pushButton_3)
        self.pushButton_5 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_5.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon7)
        self.pushButton_5.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_5.setFlat(True)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_7.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_4.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (6).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon8)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setFlat(True)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_7.addWidget(self.pushButton_4)
        self.pushButton_7 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_7.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (2).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon9)
        self.pushButton_7.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_7.setFlat(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_7.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_8.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (5).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon10)
        self.pushButton_8.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_8.setFlat(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_7.addWidget(self.pushButton_8)
        self.pushButton_11 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_11.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (4).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon11)
        self.pushButton_11.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_11.setFlat(True)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_7.addWidget(self.pushButton_11)
        self.pushButton_10 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_10.setText("")
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (7).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon12)
        self.pushButton_10.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_10.setFlat(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_7.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_9.setText("")
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/icons/icons/pngegg (11).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon13)
        self.pushButton_9.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_9.setFlat(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_7.addWidget(self.pushButton_9)
        self.pushButton_6 = QtWidgets.QPushButton(self.tool_box_2)
        self.pushButton_6.setText("")
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/icons/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon14)
        self.pushButton_6.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_6.setFlat(True)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_7.addWidget(self.pushButton_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_7.addWidget(self.tool_box_2)
        self.horizontalLayout_8.addLayout(self.verticalLayout_7)
        self.stackedWidget.addWidget(self.thumbnail_page)
        self.new_page = QtWidgets.QWidget()
        self.new_page.setObjectName("new_page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.new_page)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_9.addLayout(self.verticalLayout_9)
        self.stackedWidget.addWidget(self.new_page)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.verticalLayout_2.addWidget(self.frame_mian_body)
        self.layoutWidget = QtWidgets.QWidget(self.central_widget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        MainWindow.setCentralWidget(self.central_widget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.header.setText(_translate("MainWindow", "脊椎檢測DICOM"))
        self.menu_toggle.setText(_translate("MainWindow", "   MENU"))
        self.add_patient.setText(_translate("MainWindow", "  Add Patient"))
        self.search.setText(_translate("MainWindow", "Search"))
        self.patients.setText(_translate("MainWindow", "Patients"))
        __sortingEnabled = self.patient_list.isSortingEnabled()
        self.patient_list.setSortingEnabled(False)
        item = self.patient_list.item(0)
        item.setText(_translate("MainWindow", "1"))
        self.patient_list.setSortingEnabled(__sortingEnabled)
        self.recently_viewed.setText(_translate("MainWindow", "Recently Viewed"))
        self.patients_label.setText(_translate("MainWindow", "Patients"))
        self.search_no_label.setText(_translate("MainWindow", "Search No."))
        self.photo.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label.setText(_translate("MainWindow", "TextLabel"))

import generatedUiFile.res.nike_app_rc
